### PR TITLE
impl Clone for iterators & document edge order

### LINKED ISSUE #49: Investigate what we can guarantee about edge order
W.r.t order of insertion vs order in neighbors()

### PR DESCRIPTION
**Pull request by bluss**
Fixes #49

### CODE REVIEW

**Comment by bluss** [comment]
cc @mitchmindtree This is the order that's always present. Removals don't affect order of the remaining edges (in the neighbors() iteration).

**Comment by mitchmindtree** [comment]
Ah yep, I was using [this](https://github.com/bluss/petulant-avenger-graphlibrary/pull/50/files#diff-a0c94d0c1540ede7afa6f3cbdb8c8948R668) as a heuristic for the instantiation order of widgets in conrod, but ended up opting to explicitly track the order as the heuristic didn't work out for the use case in conrod.

**Comment by bluss** [comment]
Aha I see, what behavior would you need? I'm not sure much else could be provided. The edge lists are basically singly linked lists, so we add by appending in front.

**Comment by mitchmindtree** [comment]
Yeah I think it's probably not petgraph's issue to worry too much about ordering etc, I think what you've done here by explicitly stating the behaviour in the docs is plenty enough :+1:

**Comment by bluss** [comment]
ok, great. :cherries:

**Pull request merged**
